package main

import (
	"bufio"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/ams-tech/nixos-kaiba-network/provisioning/internal/provisioning/physicalrpi5"
	"github.com/ams-tech/nixos-kaiba-network/provisioning/internal/provisioning/rpi5"
)

const (
	stateSchema       = "kaiba.provisioning.development-secure-boot-state/v1alpha1"
	resultSchema      = "kaiba.provisioning.development-secure-boot-result/v1alpha1"
	stateRoot         = "/var/lib/kaiba-development-secure-boot"
	statePath         = stateRoot + "/state.json"
	resultPath        = stateRoot + "/result.json"
	uartEvidencePath  = stateRoot + "/signed-boot-uart.log"
	lockPath          = stateRoot + "/run.lock"
	zeroCustomerKey   = "0000000000000000000000000000000000000000000000000000000000000000"
	signedBootMarker  = "KAIBA_SECURE_BOOT_EVIDENCE=pass"
	maximumOutput     = 256 * 1024
	rpibootTimeout    = 2 * time.Minute
	uartTimeout       = 3 * time.Minute
	targetWaitTimeout = 90 * time.Second
)

// All of these values are generated by Nix from one verified signed release
// and one fixed physical development lane. There are deliberately no runtime
// flags for artifacts, device paths, or target identity.
var (
	rpibootBinary                  string
	freshReadbackBundle            string
	freshCommitBundle              string
	ownedReadbackBundle            string
	expectedCustomerKeyHash        string
	expectedEEPROMHash             string
	expectedBootImageDigest        string
	signedReleaseManifestDigest    string
	expectedTargetFingerprint      string
	fixedRPIBootSysfsPath          string
	fixedUARTPath                  string
	stationID                      string
	laneID                         string
	stationSourceRevision          string
	payloadSourceRevision          string
	hardwareQualificationDigest    string
	manualLaneQualificationDigest  string
	unfusedCompatibilityUARTDigest string
)

var (
	hexDigestPattern = regexp.MustCompile(`^[0-9a-f]{64}$`)
	shaDigestPattern = regexp.MustCompile(`^sha256:[0-9a-f]{64}$`)
	revisionPattern  = regexp.MustCompile(`^[0-9a-f]{40}$|^[0-9a-f]{64}$`)
	usbNamePattern   = regexp.MustCompile(`^[0-9]+-[0-9]+(?:\.[0-9]+)*$`)
)

type runState struct {
	SchemaVersion  string            `json:"schema_version"`
	Status         string            `json:"status"`
	StartedAt      time.Time         `json:"started_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
	Release        releaseIdentity   `json:"release"`
	Lane           laneIdentity      `json:"lane"`
	PreObservation *rpi5.Observation `json:"pre_observation,omitempty"`
	Commit         *rpi5.Observation `json:"commit,omitempty"`
	OwnedReadback  *rpi5.Observation `json:"owned_readback,omitempty"`
	CommitOutput   string            `json:"commit_output_digest,omitempty"`
	UARTOutput     string            `json:"uart_output_digest,omitempty"`
}

type releaseIdentity struct {
	StationSourceRevision       string `json:"station_source_revision"`
	PayloadSourceRevision       string `json:"payload_source_revision"`
	SignedReleaseManifestDigest string `json:"signed_release_manifest_digest"`
	BootImageDigest             string `json:"boot_image_digest"`
	CustomerKeyHash             string `json:"customer_key_hash"`
	EEPROMHash                  string `json:"eeprom_hash"`
}

type laneIdentity struct {
	StationID                      string `json:"station_id"`
	LaneID                         string `json:"lane_id"`
	RPIBootSysfsPath               string `json:"rpiboot_sysfs_path"`
	UARTPath                       string `json:"uart_path"`
	TargetFingerprint              string `json:"target_fingerprint"`
	HardwareQualificationDigest    string `json:"hardware_qualification_digest"`
	ManualLaneQualificationDigest  string `json:"manual_lane_qualification_digest"`
	UnfusedCompatibilityUARTDigest string `json:"unfused_compatibility_uart_digest"`
}

type result struct {
	SchemaVersion  string          `json:"schema_version"`
	Status         string          `json:"status"`
	CompletedAt    time.Time       `json:"completed_at"`
	Release        releaseIdentity `json:"release"`
	Lane           laneIdentity    `json:"lane"`
	CustomerKey    string          `json:"customer_key_hash"`
	EEPROMHash     string          `json:"eeprom_hash"`
	EEPROMObserved bool            `json:"eeprom_hash_directly_observed"`
	UARTDigest     string          `json:"uart_evidence_digest"`
	UARTPath       string          `json:"uart_evidence_path"`
}

type boundedBuffer struct {
	bytes.Buffer
	overflow bool
}

func (buffer *boundedBuffer) Write(value []byte) (int, error) {
	count := len(value)
	remaining := maximumOutput - buffer.Len()
	if remaining > 0 {
		if remaining > len(value) {
			remaining = len(value)
		}
		_, _ = buffer.Buffer.Write(value[:remaining])
	}
	if count > remaining {
		buffer.overflow = true
	}
	return count, nil
}

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	if err := run(ctx, os.Args[1:], os.Stdin, os.Stdout); err != nil {
		fmt.Fprintf(os.Stderr, "kaiba-secure-boot: %v\n", err)
		os.Exit(1)
	}
}

func run(ctx context.Context, arguments []string, input io.Reader, output io.Writer) error {
	if err := validateBuildConfiguration(); err != nil {
		return err
	}
	if len(arguments) != 1 {
		return errors.New("usage: kaiba-secure-boot {inventory|status|run|reconcile}")
	}
	switch arguments[0] {
	case "inventory":
		return writeJSON(output, struct {
			Release releaseIdentity `json:"release"`
			Lane    laneIdentity    `json:"lane"`
		}{compiledRelease(), compiledLane()})
	case "status":
		return printStatus(output)
	case "run", "reconcile":
	default:
		return errors.New("usage: kaiba-secure-boot {inventory|status|run|reconcile}")
	}
	if os.Geteuid() != 0 {
		return errors.New("the hardware operation must run as root (use the installed kaiba-secure-boot wrapper)")
	}
	if err := os.MkdirAll(stateRoot, 0o700); err != nil {
		return fmt.Errorf("create evidence directory: %w", err)
	}
	if err := os.Chmod(stateRoot, 0o700); err != nil {
		return fmt.Errorf("protect evidence directory: %w", err)
	}
	lock, err := acquireLock()
	if err != nil {
		return err
	}
	defer lock.Close()

	state, found, err := loadState()
	if err != nil {
		return err
	}
	if found && !stateMatchesBuild(state) {
		return errors.New("existing durable state belongs to a different release, lane, or target")
	}
	reader := bufio.NewReader(input)
	if arguments[0] == "reconcile" {
		return reconcile(ctx, reader, output, state, found)
	}
	return execute(ctx, reader, output, state, found)
}

func execute(ctx context.Context, reader *bufio.Reader, output io.Writer, state runState, found bool) error {
	if found && state.Status == "complete" {
		if _, err := os.Stat(resultPath); errors.Is(err, os.ErrNotExist) {
			if err := publishResult(state); err != nil {
				return fmt.Errorf("restore missing final result from complete durable state: %w", err)
			}
		} else if err != nil {
			return err
		}
		fmt.Fprintf(output, "SECURE BOOT ALREADY VERIFIED: %s\n", resultPath)
		return nil
	}
	if found && state.Status == "commit_started" {
		return errors.New("the prior commit response is uncertain; run: kaiba-secure-boot reconcile")
	}
	if !found || state.Status == "preobserved" || state.Status == "commit_not_applied" {
		observation, err := preobserve(ctx, reader, output)
		if err != nil {
			return err
		}
		now := time.Now().UTC()
		state = runState{
			SchemaVersion: stateSchema, Status: "preobserved", StartedAt: now, UpdatedAt: now,
			Release: compiledRelease(), Lane: compiledLane(), PreObservation: &observation,
		}
		if err := saveState(state); err != nil {
			return err
		}
		committed, outputDigest, err := commit(ctx, reader, output, state)
		if err != nil {
			return err
		}
		state.Status = "commit_verified"
		state.UpdatedAt = time.Now().UTC()
		state.Commit = &committed
		state.CommitOutput = outputDigest
		if err := saveState(state); err != nil {
			return err
		}
	}
	if state.Status == "commit_verified" {
		owned, err := ownedReadback(ctx, reader, output)
		if err != nil {
			return err
		}
		state.Status = "readback_verified"
		state.UpdatedAt = time.Now().UTC()
		state.OwnedReadback = &owned
		if err := saveState(state); err != nil {
			return err
		}
	}
	if state.Status != "readback_verified" {
		return fmt.Errorf("unsupported durable state %q", state.Status)
	}
	uart, err := os.ReadFile(uartEvidencePath)
	if errors.Is(err, os.ErrNotExist) {
		uart, err = signedBoot(ctx, reader, output)
		if err != nil {
			return err
		}
		if err := writeNewFile(uartEvidencePath, uart); err != nil {
			return fmt.Errorf("write UART evidence: %w", err)
		}
	} else if err != nil {
		return fmt.Errorf("read existing UART evidence: %w", err)
	} else if err := validateSignedBootEvidence(uart); err != nil {
		return fmt.Errorf("existing UART evidence is invalid: %w", err)
	}
	uartDigest := digestBytes(uart)
	state.Status = "complete"
	state.UpdatedAt = time.Now().UTC()
	state.UARTOutput = uartDigest
	if err := saveState(state); err != nil {
		return err
	}
	if err := publishResult(state); err != nil {
		return fmt.Errorf("write final result: %w", err)
	}
	fmt.Fprintf(output, "SECURE BOOT VERIFIED\nRESULT=%s\nUART=%s\n", resultPath, uartEvidencePath)
	return nil
}

func publishResult(state runState) error {
	if state.Status != "complete" || state.OwnedReadback == nil || state.UARTOutput == "" {
		return errors.New("complete state lacks readback or UART evidence")
	}
	if _, err := os.Stat(uartEvidencePath); err != nil {
		return fmt.Errorf("final UART evidence is unavailable: %w", err)
	}
	final := result{
		SchemaVersion: resultSchema, Status: "secure_boot_verified", CompletedAt: state.UpdatedAt,
		Release: state.Release, Lane: state.Lane,
		CustomerKey: "sha256:" + state.OwnedReadback.CustomerKeyHash,
		EEPROMHash:  "sha256:" + expectedEEPROMHash,
		EEPROMObserved: state.OwnedReadback.EEPROMHash == expectedEEPROMHash ||
			(state.Commit != nil && state.Commit.EEPROMHash == expectedEEPROMHash),
		UARTDigest: state.UARTOutput, UARTPath: uartEvidencePath,
	}
	return writeNewJSON(resultPath, final)
}

func preobserve(ctx context.Context, reader *bufio.Reader, output io.Writer) (rpi5.Observation, error) {
	if err := promptDisconnected(ctx, reader, output); err != nil {
		return rpi5.Observation{}, err
	}
	fmt.Fprintln(output, "PRE-OBSERVATION: blank key state on the exact target")
	if err := promptRPIBoot(ctx, reader, output); err != nil {
		return rpi5.Observation{}, err
	}
	observation, _, commandErr, err := runRPIBoot(ctx, freshReadbackBundle)
	if err != nil {
		return rpi5.Observation{}, err
	}
	if err := validateFresh(observation); err != nil {
		return rpi5.Observation{}, err
	}
	if commandErr != nil {
		fmt.Fprintf(output, "NOTE: rpiboot exited with %v after returning a complete blank-state readback.\n", commandErr)
	}
	fmt.Fprintf(output, "FRESH TARGET VERIFIED: %s\n", observation.TargetFingerprint)
	return observation, nil
}

func commit(ctx context.Context, reader *bufio.Reader, output io.Writer, state runState) (rpi5.Observation, string, error) {
	if err := promptDisconnected(ctx, reader, output); err != nil {
		return rpi5.Observation{}, "", err
	}
	fmt.Fprintln(output, "COMMIT: program the v0.1.6 customer key and signed EEPROM")
	if err := promptRPIBoot(ctx, reader, output); err != nil {
		return rpi5.Observation{}, "", err
	}
	phrase := "BURN V0.1.6 " + strings.ToUpper(strings.TrimPrefix(expectedTargetFingerprint, "sha256:")[:16])
	fmt.Fprintf(output, "This next payload irreversibly programs OTP on %s.\nType exactly: %s\n> ", expectedTargetFingerprint, phrase)
	confirmation, err := readLine(ctx, reader)
	if err != nil {
		return rpi5.Observation{}, "", err
	}
	if confirmation != phrase {
		return rpi5.Observation{}, "", errors.New("irreversible confirmation did not match")
	}
	state.Status = "commit_started"
	state.UpdatedAt = time.Now().UTC()
	if err := saveState(state); err != nil {
		return rpi5.Observation{}, "", err
	}
	observation, raw, commandErr, err := runRPIBoot(ctx, freshCommitBundle)
	if err != nil {
		return rpi5.Observation{}, "", fmt.Errorf("commit outcome is uncertain; do not repeat it; run reconcile: %w", err)
	}
	if err := validateCommit(observation); err != nil {
		return rpi5.Observation{}, "", fmt.Errorf("commit outcome is uncertain; do not repeat it; run reconcile: %w", err)
	}
	if commandErr != nil {
		fmt.Fprintf(output, "NOTE: rpiboot exited with %v after returning a complete verified commit result.\n", commandErr)
	}
	fmt.Fprintln(output, "OTP AND EEPROM COMMIT VERIFIED")
	return observation, digestBytes(raw), nil
}

func ownedReadback(ctx context.Context, reader *bufio.Reader, output io.Writer) (rpi5.Observation, error) {
	if err := promptDisconnected(ctx, reader, output); err != nil {
		return rpi5.Observation{}, err
	}
	fmt.Fprintln(output, "READBACK: verify the programmed key and EEPROM")
	if err := promptRPIBoot(ctx, reader, output); err != nil {
		return rpi5.Observation{}, err
	}
	observation, _, commandErr, err := runRPIBoot(ctx, ownedReadbackBundle)
	if err != nil {
		return rpi5.Observation{}, err
	}
	if err := validateOwned(observation); err != nil {
		return rpi5.Observation{}, err
	}
	if commandErr != nil {
		fmt.Fprintf(output, "NOTE: rpiboot exited with %v after returning a complete owned readback.\n", commandErr)
	}
	fmt.Fprintln(output, "PROGRAMMED STATE READBACK VERIFIED")
	return observation, nil
}

func signedBoot(ctx context.Context, reader *bufio.Reader, output io.Writer) ([]byte, error) {
	if err := promptDisconnected(ctx, reader, output); err != nil {
		return nil, err
	}
	fmt.Fprintln(output, "SIGNED BOOT: UART is being armed before normal power is connected")
	uart := physicalrpi5.FileUART{}
	evidence, err := uart.Capture(ctx, fixedUARTPath, []byte(signedBootMarker), maximumOutput, uartTimeout, func() error {
		fmt.Fprintln(output, "Leave BOOTSEL untouched. Ensure the verified signed v0.1.6 SD card is installed.")
		fmt.Fprintln(output, "Keep the provisioning USB disconnected, connect the normal Pi power supply, then press Enter.")
		_, promptErr := readLine(ctx, reader)
		return promptErr
	})
	if err != nil {
		return nil, fmt.Errorf("capture signed-boot UART evidence: %w", err)
	}
	if err := validateSignedBootEvidence(evidence); err != nil {
		return nil, err
	}
	return evidence, nil
}

func reconcile(ctx context.Context, reader *bufio.Reader, output io.Writer, state runState, found bool) error {
	if !found || state.Status != "commit_started" {
		return errors.New("reconcile is only valid after a durable uncertain commit attempt")
	}
	if err := promptDisconnected(ctx, reader, output); err != nil {
		return err
	}
	fmt.Fprintln(output, "RECONCILE: read the target; this will not repeat the OTP operation")
	if err := promptRPIBoot(ctx, reader, output); err != nil {
		return err
	}
	observation, _, commandErr, err := runRPIBoot(ctx, ownedReadbackBundle)
	if err == nil {
		if ownedErr := validateOwned(observation); ownedErr == nil {
			if commandErr != nil {
				fmt.Fprintf(output, "NOTE: rpiboot exited with %v after returning a complete owned readback.\n", commandErr)
			}
			state.Status = "readback_verified"
			state.UpdatedAt = time.Now().UTC()
			state.Commit = &observation
			state.OwnedReadback = &observation
			if err := saveState(state); err != nil {
				return err
			}
			fmt.Fprintln(output, "COMMIT WAS APPLIED AND READ BACK. Run: kaiba-secure-boot run")
			return nil
		}
	}

	// An owned recovery payload may be rejected when the OTP commit was not
	// applied. That rejection consumes the RPIBOOT session, so use a second,
	// physically fresh connection before trying the read-only blank-target
	// bundle. A programmed board will reject that unsigned bundle; a complete
	// blank observation proves that a new explicit commit attempt is safe.
	fmt.Fprintln(output, "Owned readback did not establish the programmed state.")
	if err := promptDisconnected(ctx, reader, output); err != nil {
		return err
	}
	fmt.Fprintln(output, "RECONCILE: check for the original blank state on a fresh connection")
	if err := promptRPIBoot(ctx, reader, output); err != nil {
		return err
	}
	freshObservation, _, freshCommandErr, freshRunErr := runRPIBoot(ctx, freshReadbackBundle)
	if freshRunErr == nil && validateFresh(freshObservation) == nil {
		if freshCommandErr != nil {
			fmt.Fprintf(output, "NOTE: rpiboot exited with %v after returning a complete blank-state readback.\n", freshCommandErr)
		}
		state.Status = "commit_not_applied"
		state.UpdatedAt = time.Now().UTC()
		state.PreObservation = &freshObservation
		state.Commit = nil
		state.OwnedReadback = nil
		state.CommitOutput = ""
		if err := saveState(state); err != nil {
			return err
		}
		fmt.Fprintln(output, "COMMIT WAS NOT APPLIED. Run kaiba-secure-boot run to make a new explicit attempt.")
		return nil
	}
	return errors.New("target state remains ambiguous; preserve evidence and do not repeat the commit")
}

func promptDisconnected(ctx context.Context, reader *bufio.Reader, output io.Writer) error {
	fmt.Fprintln(output, "Disconnect every target power source. Confirm the target LEDs are off, then press Enter.")
	if _, err := readLine(ctx, reader); err != nil {
		return err
	}
	deadline := time.Now().Add(15 * time.Second)
	for {
		targets, err := eligibleTargets()
		if err != nil {
			return err
		}
		if len(targets) == 0 {
			break
		}
		if time.Now().After(deadline) {
			return fmt.Errorf("RPIBOOT target remains present at %s", strings.Join(targets, ", "))
		}
		if err := sleep(ctx, 100*time.Millisecond); err != nil {
			return err
		}
	}
	return sleep(ctx, 2*time.Second)
}

func promptRPIBoot(ctx context.Context, reader *bufio.Reader, output io.Writer) error {
	fmt.Fprintln(output, "Hold BOOTSEL. Connect the intact provisioning USB as the target's sole power/data cable. Keep holding BOOTSEL, then press Enter.")
	if _, err := readLine(ctx, reader); err != nil {
		return err
	}
	if err := waitExactTarget(ctx); err != nil {
		return err
	}
	fmt.Fprintln(output, "RPIBOOT observed on the fixed lane. Release BOOTSEL, then press Enter.")
	if _, err := readLine(ctx, reader); err != nil {
		return err
	}
	return requireExactTarget()
}

func runRPIBoot(ctx context.Context, bundle string) (rpi5.Observation, []byte, error, error) {
	if err := requireExactTarget(); err != nil {
		return rpi5.Observation{}, nil, nil, err
	}
	pin, err := (physicalrpi5.OSFileSystem{}).PinUSBInstance(fixedRPIBootSysfsPath)
	if err != nil {
		return rpi5.Observation{}, nil, nil, fmt.Errorf("pin fixed RPIBOOT device: %w", err)
	}
	defer pin.Close()
	if err := pin.Verify(); err != nil {
		return rpi5.Observation{}, nil, nil, err
	}
	commandCtx, cancel := context.WithTimeout(ctx, rpibootTimeout)
	defer cancel()
	stdout := &boundedBuffer{}
	stderr := &boundedBuffer{}
	command := exec.CommandContext(commandCtx, rpibootBinary, "-p", filepath.Base(fixedRPIBootSysfsPath), "-d", bundle)
	command.Stdout = stdout
	command.Stderr = stderr
	if err := requireExactTarget(); err != nil {
		return rpi5.Observation{}, nil, nil, err
	}
	if err := pin.Verify(); err != nil {
		return rpi5.Observation{}, nil, nil, err
	}
	commandErr := command.Run()
	if stdout.overflow || stderr.overflow {
		return rpi5.Observation{}, nil, commandErr, errors.New("rpiboot output exceeded its fixed bound")
	}
	metadata, extractErr := rpi5.ExtractMetadataObject(stdout.Bytes())
	if extractErr != nil {
		diagnostic := strings.TrimSpace(stderr.String())
		if len(diagnostic) > 2048 {
			diagnostic = diagnostic[:2048]
		}
		return rpi5.Observation{}, stdout.Bytes(), commandErr, fmt.Errorf("extract rpiboot metadata (stderr=%q): %w", diagnostic, extractErr)
	}
	observation, parseErr := rpi5.ParseMetadata(metadata)
	if parseErr != nil {
		return rpi5.Observation{}, stdout.Bytes(), commandErr, fmt.Errorf("parse rpiboot metadata: %w", parseErr)
	}
	return observation, append([]byte(nil), stdout.Bytes()...), commandErr, nil
}

func validateFresh(observation rpi5.Observation) error {
	if err := validateIdentity(observation); err != nil {
		return err
	}
	if observation.CustomerKeyHash != zeroCustomerKey || observation.CustomerKeyState != "unset" {
		return errors.New("target customer key is not blank")
	}
	if observation.VideoCoreJTAGLocked {
		return errors.New("fresh target unexpectedly has VideoCore JTAG locked")
	}
	if len(observation.MutationSuccess) != 0 {
		return errors.New("read-only observation reported a mutation")
	}
	return nil
}

func validateCommit(observation rpi5.Observation) error {
	if err := validateOwned(observation); err != nil {
		return err
	}
	if observation.EEPROMHash != expectedEEPROMHash {
		return errors.New("commit response did not attest the expected EEPROM hash")
	}
	if strings.ToLower(observation.UpstreamFields["EEPROM_UPDATE"]) != "success" ||
		strings.ToLower(observation.UpstreamFields["SECURE_BOOT_PROVISION"]) != "success" {
		return errors.New("commit response did not report EEPROM_UPDATE=success and SECURE_BOOT_PROVISION=success")
	}
	return nil
}

func validateOwned(observation rpi5.Observation) error {
	if err := validateIdentity(observation); err != nil {
		return err
	}
	if observation.CustomerKeyHash != expectedCustomerKeyHash || observation.CustomerKeyState != "set" {
		return errors.New("programmed customer key does not match the signed release")
	}
	// Raspberry Pi's metadata-only owned readback is allowed to omit
	// EEPROM_HASH. A present value is strict; the commit response and final
	// signed UART boot provide the other two postconditions.
	if observation.EEPROMHash != "" && observation.EEPROMHash != expectedEEPROMHash {
		return errors.New("programmed EEPROM does not match the signed release")
	}
	return nil
}

func validateIdentity(observation rpi5.Observation) error {
	if observation.TargetFingerprint != expectedTargetFingerprint {
		return fmt.Errorf("target fingerprint %s does not match fixed target %s", observation.TargetFingerprint, expectedTargetFingerprint)
	}
	return nil
}

func validateSignedBootEvidence(evidence []byte) error {
	var record string
	for _, line := range strings.Split(string(evidence), "\n") {
		line = strings.TrimSuffix(line, "\r")
		if !strings.HasPrefix(line, signedBootMarker) {
			continue
		}
		if record != "" {
			return errors.New("UART evidence contains multiple secure-boot pass records")
		}
		record = line
	}
	if record == "" {
		return errors.New("UART secure-boot pass record is absent")
	}
	fields := strings.Fields(record)
	if len(fields) != 6 || fields[0] != signedBootMarker {
		return errors.New("UART secure-boot pass record has an unexpected shape")
	}
	values := make(map[string]string, 5)
	for _, field := range fields[1:] {
		key, value, ok := strings.Cut(field, "=")
		if !ok || key == "" || value == "" {
			return errors.New("UART secure-boot pass record contains a malformed field")
		}
		if _, exists := values[key]; exists {
			return fmt.Errorf("UART secure-boot pass record repeats %s", key)
		}
		values[key] = value
	}
	if len(values) != 5 || values["boot_img_sha256"] != expectedBootImageDigest ||
		values["root"] != "/dev/mapper/root" || values["rollback"] != "unimplemented" ||
		values["enrollment_ready"] != "false" {
		return errors.New("UART secure-boot pass record differs from the signed image or fixed boot policy")
	}
	signed := values["signed"]
	if len(signed) != 8 || strings.ToLower(signed) != signed {
		return errors.New("UART signed field is not canonical 32-bit hexadecimal")
	}
	value, err := strconv.ParseUint(signed, 16, 32)
	if err != nil || value&8 != 8 {
		return errors.New("UART signed field does not show the customer-key OTP bit")
	}
	return nil
}

func eligibleTargets() ([]string, error) {
	root := filepath.Dir(fixedRPIBootSysfsPath)
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, fmt.Errorf("read USB sysfs: %w", err)
	}
	var targets []string
	for _, entry := range entries {
		if !usbNamePattern.MatchString(entry.Name()) {
			continue
		}
		base := filepath.Join(root, entry.Name())
		vendor, vendorErr := os.ReadFile(filepath.Join(base, "idVendor"))
		product, productErr := os.ReadFile(filepath.Join(base, "idProduct"))
		if vendorErr == nil && productErr == nil && strings.EqualFold(strings.TrimSpace(string(vendor)), rpi5.BroadcomVendorID) && strings.EqualFold(strings.TrimSpace(string(product)), rpi5.BCM2712ProductID) {
			targets = append(targets, base)
		}
	}
	return targets, nil
}

func requireExactTarget() error {
	targets, err := eligibleTargets()
	if err != nil {
		return err
	}
	if len(targets) != 1 || targets[0] != fixedRPIBootSysfsPath {
		return fmt.Errorf("expected exactly %s, observed %v", fixedRPIBootSysfsPath, targets)
	}
	return nil
}

func waitExactTarget(ctx context.Context) error {
	waitCtx, cancel := context.WithTimeout(ctx, targetWaitTimeout)
	defer cancel()
	for {
		targets, err := eligibleTargets()
		if err != nil {
			return err
		}
		if len(targets) == 1 && targets[0] == fixedRPIBootSysfsPath {
			return nil
		}
		if len(targets) != 0 {
			return fmt.Errorf("unexpected RPIBOOT topology while waiting for %s: %v", fixedRPIBootSysfsPath, targets)
		}
		if err := sleep(waitCtx, 100*time.Millisecond); err != nil {
			return errors.New("timed out waiting for the exact RPIBOOT target")
		}
	}
}

func validateBuildConfiguration() error {
	for label, value := range map[string]string{
		"rpiboot": rpibootBinary, "fresh readback": freshReadbackBundle,
		"fresh commit": freshCommitBundle, "owned readback": ownedReadbackBundle,
		"RPIBOOT sysfs": fixedRPIBootSysfsPath, "UART": fixedUARTPath,
	} {
		if value == "" || !filepath.IsAbs(value) || filepath.Clean(value) != value {
			return fmt.Errorf("compiled %s path is invalid", label)
		}
	}
	if !shaDigestPattern.MatchString(expectedTargetFingerprint) ||
		!shaDigestPattern.MatchString(expectedBootImageDigest) ||
		!shaDigestPattern.MatchString(signedReleaseManifestDigest) ||
		!shaDigestPattern.MatchString(hardwareQualificationDigest) ||
		!shaDigestPattern.MatchString(manualLaneQualificationDigest) ||
		!shaDigestPattern.MatchString(unfusedCompatibilityUARTDigest) ||
		!hexDigestPattern.MatchString(expectedCustomerKeyHash) ||
		!hexDigestPattern.MatchString(expectedEEPROMHash) ||
		!revisionPattern.MatchString(stationSourceRevision) ||
		!revisionPattern.MatchString(payloadSourceRevision) || stationID == "" || laneID == "" {
		return errors.New("compiled release or lane identity is invalid")
	}
	if filepath.Base(fixedRPIBootSysfsPath) == "." || !usbNamePattern.MatchString(filepath.Base(fixedRPIBootSysfsPath)) {
		return errors.New("compiled RPIBOOT sysfs path is invalid")
	}
	return nil
}

func compiledRelease() releaseIdentity {
	return releaseIdentity{stationSourceRevision, payloadSourceRevision, signedReleaseManifestDigest, expectedBootImageDigest, "sha256:" + expectedCustomerKeyHash, "sha256:" + expectedEEPROMHash}
}

func compiledLane() laneIdentity {
	return laneIdentity{stationID, laneID, fixedRPIBootSysfsPath, fixedUARTPath, expectedTargetFingerprint, hardwareQualificationDigest, manualLaneQualificationDigest, unfusedCompatibilityUARTDigest}
}

func stateMatchesBuild(state runState) bool {
	return state.SchemaVersion == stateSchema && state.Release == compiledRelease() && state.Lane == compiledLane()
}

func acquireLock() (*os.File, error) {
	file, err := os.OpenFile(lockPath, os.O_CREATE|os.O_RDWR|syscall.O_NOFOLLOW, 0o600)
	if err != nil {
		return nil, fmt.Errorf("open run lock: %w", err)
	}
	if err := syscall.Flock(int(file.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
		file.Close()
		return nil, errors.New("another secure-boot operation is already running")
	}
	return file, nil
}

func loadState() (runState, bool, error) {
	file, err := os.OpenFile(statePath, os.O_RDONLY|syscall.O_NOFOLLOW, 0)
	if errors.Is(err, os.ErrNotExist) {
		return runState{}, false, nil
	}
	if err != nil {
		return runState{}, false, err
	}
	defer file.Close()
	var state runState
	decoder := json.NewDecoder(io.LimitReader(file, 1024*1024))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&state); err != nil {
		return runState{}, false, fmt.Errorf("decode durable state: %w", err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		return runState{}, false, errors.New("durable state contains trailing data")
	}
	return state, true, nil
}

func saveState(state runState) error {
	return replaceJSON(statePath, state)
}

func replaceJSON(path string, value any) error {
	directory := filepath.Dir(path)
	temporary, err := os.CreateTemp(directory, ".state-*")
	if err != nil {
		return err
	}
	name := temporary.Name()
	defer os.Remove(name)
	if err := temporary.Chmod(0o600); err != nil {
		temporary.Close()
		return err
	}
	encoder := json.NewEncoder(temporary)
	encoder.SetEscapeHTML(false)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(value); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Sync(); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	if err := os.Rename(name, path); err != nil {
		return err
	}
	dir, err := os.Open(directory)
	if err != nil {
		return err
	}
	defer dir.Close()
	return dir.Sync()
}

func writeNewJSON(path string, value any) error {
	var buffer bytes.Buffer
	encoder := json.NewEncoder(&buffer)
	encoder.SetEscapeHTML(false)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(value); err != nil {
		return err
	}
	return writeNewFile(path, buffer.Bytes())
}

func writeNewFile(path string, data []byte) error {
	file, err := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY|syscall.O_NOFOLLOW, 0o600)
	if err != nil {
		return err
	}
	remove := true
	defer func() {
		file.Close()
		if remove {
			os.Remove(path)
		}
	}()
	if _, err := file.Write(data); err != nil {
		return err
	}
	if err := file.Sync(); err != nil {
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	remove = false
	dir, err := os.Open(filepath.Dir(path))
	if err != nil {
		return err
	}
	defer dir.Close()
	return dir.Sync()
}

func printStatus(output io.Writer) error {
	if data, err := os.ReadFile(resultPath); err == nil {
		_, err = output.Write(data)
		return err
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	state, found, err := loadState()
	if err != nil {
		return err
	}
	if !found {
		fmt.Fprintln(output, "not_started")
		return nil
	}
	return writeJSON(output, state)
}

func writeJSON(output io.Writer, value any) error {
	encoder := json.NewEncoder(output)
	encoder.SetEscapeHTML(false)
	encoder.SetIndent("", "  ")
	return encoder.Encode(value)
}

func readLine(ctx context.Context, reader *bufio.Reader) (string, error) {
	type response struct {
		line string
		err  error
	}
	result := make(chan response, 1)
	go func() {
		line, err := reader.ReadString('\n')
		result <- response{strings.TrimSuffix(strings.TrimSuffix(line, "\n"), "\r"), err}
	}()
	select {
	case <-ctx.Done():
		return "", ctx.Err()
	case value := <-result:
		if value.err != nil && !errors.Is(value.err, io.EOF) {
			return "", value.err
		}
		return value.line, nil
	}
}

func sleep(ctx context.Context, duration time.Duration) error {
	timer := time.NewTimer(duration)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}

func digestBytes(value []byte) string {
	digest := sha256.Sum256(value)
	return "sha256:" + hex.EncodeToString(digest[:])
}
